Resources:
  DrsRecoveryInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: drs-recovery-instance-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSElasticDisasterRecoveryRecoveryInstancePolicy
